<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<IsAotCompatible>true</IsAotCompatible>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<PropertyGroup>
		<PackageId>MulticastFunc</PackageId>
		<Version>3.0.0</Version>
		<Authors>ent3m</Authors>
		<Title>MulticastFunc</Title>
		<Description>A high-performance, drop-in alternative to Func that retrieves the return values of all invocations instead of only the final one.</Description>

		<PackageLicenseExpression>MIT</PackageLicenseExpression>

		<PackageProjectUrl>https://github.com/ent3m/MulticastFunc</PackageProjectUrl>
		<RepositoryUrl>https://github.com/ent3m/MulticastFunc</RepositoryUrl>
		<RepositoryType>git</RepositoryType>

		<PackageReadmeFile>README-NUGET.md</PackageReadmeFile>
		<PackageTags>delegate;multicast;performance</PackageTags>

		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>

		<PackageReleaseNotes>Refactor to improve performance, match Delegate logic, and introduce InvokeAll.</PackageReleaseNotes>
	</PropertyGroup>

	<ItemGroup>
		<None Include="README-NUGET.md" Pack="true" PackagePath="/" />
	</ItemGroup>

</Project>
